package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/foxzi/baton/internal/exitcode"
	"github.com/foxzi/baton/internal/packs"
)

// demoSpec is a small OpenAPI 3 document with two operations: a path
// parameter typed as an integer and a query parameter typed as an enum, so
// neither trips the plain-string flow-scalar issue that a bare `type:
// string` parameter would.
const demoSpec = `
openapi: 3.0.3
info:
  title: Demo API
  version: "1"
paths:
  /things/{id}:
    get:
      operationId: getThing
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        "200": { description: ok }
  /things:
    get:
      operationId: listThings
      parameters:
        - name: status
          in: query
          required: false
          schema: { type: string, enum: [open, closed] }
      responses:
        "200": { description: ok }
`

// writeSpec writes spec to a file under t.TempDir() and returns its path.
func writeSpec(t *testing.T, spec string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "openapi.yaml")
	if err := os.WriteFile(path, []byte(spec), 0o644); err != nil {
		t.Fatalf("write spec: %v", err)
	}
	return path
}

func TestApisImportGeneratesPack(t *testing.T) {
	path := writeSpec(t, demoSpec)

	var code int
	stdout, _ := captureOutput(t, func() {
		code = apisCmd([]string{"import", "--openapi", path, "--ops", "getThing"})
	})
	if code != exitcode.OK {
		t.Fatalf("exit code = %d, want %d", code, exitcode.OK)
	}
	if !strings.HasPrefix(stdout, "# generated by baton apis import") {
		t.Fatalf("output does not start with the generated header: %q", stdout)
	}
	if !strings.Contains(stdout, "pack:") || !strings.Contains(stdout, "ops:") {
		t.Fatalf("output missing pack:/ops: sections:\n%s", stdout)
	}
}

// --ops accepts a comma-separated list.
func TestApisImportOpsCommaSeparated(t *testing.T) {
	path := writeSpec(t, demoSpec)

	var code int
	stdout, _ := captureOutput(t, func() {
		code = apisCmd([]string{"import", "--openapi", path, "--ops", "getThing,listThings"})
	})
	if code != exitcode.OK {
		t.Fatalf("exit code = %d, want %d", code, exitcode.OK)
	}
	if !strings.Contains(stdout, "get_thing:") || !strings.Contains(stdout, "list_things:") {
		t.Fatalf("output missing one of the two ops:\n%s", stdout)
	}
}

// --ops can also be repeated instead of comma-separated.
func TestApisImportOpsRepeated(t *testing.T) {
	path := writeSpec(t, demoSpec)

	var code int
	stdout, _ := captureOutput(t, func() {
		code = apisCmd([]string{"import", "--openapi", path, "--ops", "getThing", "--ops", "listThings"})
	})
	if code != exitcode.OK {
		t.Fatalf("exit code = %d, want %d", code, exitcode.OK)
	}
	if !strings.Contains(stdout, "get_thing:") || !strings.Contains(stdout, "list_things:") {
		t.Fatalf("output missing one of the two ops:\n%s", stdout)
	}
}

func TestApisImportMissingOpenapiFlag(t *testing.T) {
	var code int
	_, stderr := captureOutput(t, func() {
		code = apisCmd([]string{"import", "--ops", "getThing"})
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
	if !strings.Contains(stderr, "--openapi is required") || !strings.Contains(stderr, "Usage:") {
		t.Fatalf("stderr does not report the usage: %q", stderr)
	}
}

func TestApisImportUnreadableSpec(t *testing.T) {
	path := filepath.Join(t.TempDir(), "does-not-exist.yaml")

	var code int
	captureOutput(t, func() {
		code = apisCmd([]string{"import", "--openapi", path, "--ops", "getThing"})
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
}

func TestApisUnknownSubcommand(t *testing.T) {
	var code int
	captureOutput(t, func() {
		code = apisCmd([]string{"frobnicate"})
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
}

func TestApisNoSubcommand(t *testing.T) {
	var code int
	captureOutput(t, func() {
		code = apisCmd(nil)
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
}

// The generated pack must load through packs.Parse: that is the contract
// that matters, not the exact YAML text.
func TestApisImportOutputLoadsThroughPacksParse(t *testing.T) {
	path := writeSpec(t, demoSpec)

	var code int
	stdout, _ := captureOutput(t, func() {
		code = apisCmd([]string{"import", "--openapi", path, "--ops", "getThing"})
	})
	if code != exitcode.OK {
		t.Fatalf("exit code = %d, want %d", code, exitcode.OK)
	}
	if _, err := packs.Parse([]byte(stdout), "generated.yaml"); err != nil {
		t.Fatalf("packs.Parse: %v\n--- generated ---\n%s", err, stdout)
	}
}
