package main

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/foxzi/baton/internal/exitcode"
	"github.com/foxzi/baton/internal/packs"
)

// demoSpec is a small OpenAPI 3 document with two operations: a path
// parameter typed as an integer and a query parameter typed as an enum, so
// neither trips the plain-string flow-scalar issue that a bare `type:
// string` parameter would.
const demoSpec = `
openapi: 3.0.3
info:
  title: Demo API
  version: "1"
paths:
  /things/{id}:
    get:
      operationId: getThing
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        "200": { description: ok }
  /things:
    get:
      operationId: listThings
      parameters:
        - name: status
          in: query
          required: false
          schema: { type: string, enum: [open, closed] }
      responses:
        "200": { description: ok }
`

// writeSpec writes spec to a file under t.TempDir() and returns its path.
func writeSpec(t *testing.T, spec string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "openapi.yaml")
	if err := os.WriteFile(path, []byte(spec), 0o644); err != nil {
		t.Fatalf("write spec: %v", err)
	}
	return path
}

func TestApisImportGeneratesPack(t *testing.T) {
	path := writeSpec(t, demoSpec)

	var code int
	stdout, _ := captureOutput(t, func() {
		code = apisCmd([]string{"import", "--openapi", path, "--ops", "getThing"})
	})
	if code != exitcode.OK {
		t.Fatalf("exit code = %d, want %d", code, exitcode.OK)
	}
	if !strings.HasPrefix(stdout, "# generated by baton apis import") {
		t.Fatalf("output does not start with the generated header: %q", stdout)
	}
	if !strings.Contains(stdout, "pack:") || !strings.Contains(stdout, "ops:") {
		t.Fatalf("output missing pack:/ops: sections:\n%s", stdout)
	}
}

// --ops accepts a comma-separated list.
func TestApisImportOpsCommaSeparated(t *testing.T) {
	path := writeSpec(t, demoSpec)

	var code int
	stdout, _ := captureOutput(t, func() {
		code = apisCmd([]string{"import", "--openapi", path, "--ops", "getThing,listThings"})
	})
	if code != exitcode.OK {
		t.Fatalf("exit code = %d, want %d", code, exitcode.OK)
	}
	if !strings.Contains(stdout, "get_thing:") || !strings.Contains(stdout, "list_things:") {
		t.Fatalf("output missing one of the two ops:\n%s", stdout)
	}
}

// --ops can also be repeated instead of comma-separated.
func TestApisImportOpsRepeated(t *testing.T) {
	path := writeSpec(t, demoSpec)

	var code int
	stdout, _ := captureOutput(t, func() {
		code = apisCmd([]string{"import", "--openapi", path, "--ops", "getThing", "--ops", "listThings"})
	})
	if code != exitcode.OK {
		t.Fatalf("exit code = %d, want %d", code, exitcode.OK)
	}
	if !strings.Contains(stdout, "get_thing:") || !strings.Contains(stdout, "list_things:") {
		t.Fatalf("output missing one of the two ops:\n%s", stdout)
	}
}

func TestApisImportMissingOpenapiFlag(t *testing.T) {
	var code int
	_, stderr := captureOutput(t, func() {
		code = apisCmd([]string{"import", "--ops", "getThing"})
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
	if !strings.Contains(stderr, "--openapi is required") || !strings.Contains(stderr, "Usage:") {
		t.Fatalf("stderr does not report the usage: %q", stderr)
	}
}

func TestApisImportUnreadableSpec(t *testing.T) {
	path := filepath.Join(t.TempDir(), "does-not-exist.yaml")

	var code int
	captureOutput(t, func() {
		code = apisCmd([]string{"import", "--openapi", path, "--ops", "getThing"})
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
}

func TestApisUnknownSubcommand(t *testing.T) {
	var code int
	captureOutput(t, func() {
		code = apisCmd([]string{"frobnicate"})
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
}

func TestApisNoSubcommand(t *testing.T) {
	var code int
	captureOutput(t, func() {
		code = apisCmd(nil)
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
}

// The generated pack must load through packs.Parse: that is the contract
// that matters, not the exact YAML text.
func TestApisImportOutputLoadsThroughPacksParse(t *testing.T) {
	path := writeSpec(t, demoSpec)

	var code int
	stdout, _ := captureOutput(t, func() {
		code = apisCmd([]string{"import", "--openapi", path, "--ops", "getThing"})
	})
	if code != exitcode.OK {
		t.Fatalf("exit code = %d, want %d", code, exitcode.OK)
	}
	if _, err := packs.Parse([]byte(stdout), "generated.yaml"); err != nil {
		t.Fatalf("packs.Parse: %v\n--- generated ---\n%s", err, stdout)
	}
}

// demoPackYAML is the smallest pack that packs.Parse accepts, with one op
// whose transform picks a single field out of the recorded example.
const demoPackYAML = `pack: demo
version: 1
ops:
  get_thing:
    get: /things/{id}
    params:
      id: { pattern: '^\d+$' }
    transform: '{ id: .id }'
`

func TestApisValidateNoArgs(t *testing.T) {
	var code int
	_, stderr := captureOutput(t, func() {
		code = apisCmd([]string{"validate"})
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
	if !strings.Contains(stderr, "Usage:") {
		t.Fatalf("stderr does not report usage: %q", stderr)
	}
}

func TestApisValidatePackFileWithExample(t *testing.T) {
	dir := t.TempDir()
	packPath := filepath.Join(dir, "demo.yaml")
	if err := os.WriteFile(packPath, []byte(demoPackYAML), 0o644); err != nil {
		t.Fatalf("write pack: %v", err)
	}
	examplesDir := filepath.Join(dir, "examples")
	if err := os.MkdirAll(examplesDir, 0o755); err != nil {
		t.Fatalf("mkdir examples: %v", err)
	}
	if err := os.WriteFile(filepath.Join(examplesDir, "get_thing.json"), []byte(`{"id": 1}`), 0o644); err != nil {
		t.Fatalf("write example: %v", err)
	}

	var code int
	stdout, _ := captureOutput(t, func() {
		code = apisCmd([]string{"validate", packPath})
	})
	if code != exitcode.OK {
		t.Fatalf("exit code = %d, want %d", code, exitcode.OK)
	}
	if !strings.Contains(stdout, "ok  demo.get_thing") {
		t.Fatalf("stdout missing the ok line: %q", stdout)
	}
	if !strings.Contains(stdout, "1 ops, 1 examples checked, 0 without examples") {
		t.Fatalf("stdout missing the summary line: %q", stdout)
	}
}

func TestApisValidatePackDirectoryLayout(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "pack.yaml"), []byte(demoPackYAML), 0o644); err != nil {
		t.Fatalf("write pack: %v", err)
	}
	examplesDir := filepath.Join(dir, "examples")
	if err := os.MkdirAll(examplesDir, 0o755); err != nil {
		t.Fatalf("mkdir examples: %v", err)
	}
	if err := os.WriteFile(filepath.Join(examplesDir, "get_thing.json"), []byte(`{"id": 1}`), 0o644); err != nil {
		t.Fatalf("write example: %v", err)
	}

	var code int
	captureOutput(t, func() {
		code = apisCmd([]string{"validate", dir})
	})
	if code != exitcode.OK {
		t.Fatalf("exit code = %d, want %d", code, exitcode.OK)
	}
}

func TestApisValidateDirectoryMissingPackYAML(t *testing.T) {
	dir := t.TempDir()

	var code int
	_, stderr := captureOutput(t, func() {
		code = apisCmd([]string{"validate", dir})
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
	if !strings.Contains(stderr, "no pack.yaml in") {
		t.Fatalf("stderr does not report the missing pack.yaml: %q", stderr)
	}
}

// forgeGetChangeImplementsPack is a get_change operation that fully
// conforms to forge/v1: it names its params project and id, and its
// transform yields a result the interface's schema accepts.
const forgeGetChangeImplementsPack = `pack: demo
version: 1
ops:
  get_change:
    get: /projects/{project}/changes/{id}
    params:
      project: { pattern: '^[\w./-]+$', encode: path }
      id: { pattern: '^\d+$' }
    transform: |
      { id, title, files: [ .changes[] | { path: .new_path } ] }
    implements: forge/v1.get_change
`

// forgeGetChangeImplementsExample is a recorded response that transforms
// into a value forgeGetChangeImplementsPack's implements declaration
// accepts.
const forgeGetChangeImplementsExample = `{
	"id": 7,
	"title": "Speed things up",
	"changes": [ { "new_path": "main.go" } ]
}`

func TestApisValidateImplementsOK(t *testing.T) {
	dir := t.TempDir()
	packPath := filepath.Join(dir, "demo.yaml")
	if err := os.WriteFile(packPath, []byte(forgeGetChangeImplementsPack), 0o644); err != nil {
		t.Fatalf("write pack: %v", err)
	}
	examplesDir := filepath.Join(dir, "examples")
	if err := os.MkdirAll(examplesDir, 0o755); err != nil {
		t.Fatalf("mkdir examples: %v", err)
	}
	if err := os.WriteFile(filepath.Join(examplesDir, "get_change.json"), []byte(forgeGetChangeImplementsExample), 0o644); err != nil {
		t.Fatalf("write example: %v", err)
	}

	var code int
	captureOutput(t, func() {
		code = apisCmd([]string{"validate", packPath})
	})
	if code != exitcode.OK {
		t.Fatalf("exit code = %d, want %d", code, exitcode.OK)
	}
}

func TestApisValidateImplementsWrongParamName(t *testing.T) {
	dir := t.TempDir()
	pack := `pack: demo
version: 1
ops:
  get_change:
    get: /projects/{project}/changes/{iid}
    params:
      project: { pattern: '^[\w./-]+$', encode: path }
      iid: { pattern: '^\d+$' }
    transform: |
      { id, title, files: [ .changes[] | { path: .new_path } ] }
    implements: forge/v1.get_change
`
	packPath := filepath.Join(dir, "demo.yaml")
	if err := os.WriteFile(packPath, []byte(pack), 0o644); err != nil {
		t.Fatalf("write pack: %v", err)
	}
	examplesDir := filepath.Join(dir, "examples")
	if err := os.MkdirAll(examplesDir, 0o755); err != nil {
		t.Fatalf("mkdir examples: %v", err)
	}
	if err := os.WriteFile(filepath.Join(examplesDir, "get_change.json"), []byte(forgeGetChangeImplementsExample), 0o644); err != nil {
		t.Fatalf("write example: %v", err)
	}

	var code int
	_, stderr := captureOutput(t, func() {
		code = apisCmd([]string{"validate", packPath})
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
	if !strings.Contains(stderr, `interface argument "id" is missing`) {
		t.Fatalf("stderr does not report the missing interface argument: %q", stderr)
	}
}

func TestApisValidateTransformFails(t *testing.T) {
	dir := t.TempDir()
	pack := `pack: demo
version: 1
ops:
  list_things:
    get: /things
    transform: '.id'
`
	packPath := filepath.Join(dir, "demo.yaml")
	if err := os.WriteFile(packPath, []byte(pack), 0o644); err != nil {
		t.Fatalf("write pack: %v", err)
	}
	examplesDir := filepath.Join(dir, "examples")
	if err := os.MkdirAll(examplesDir, 0o755); err != nil {
		t.Fatalf("mkdir examples: %v", err)
	}
	// The transform expects an object field but the recorded example is a
	// bare array, so the jq expression fails at run time.
	if err := os.WriteFile(filepath.Join(examplesDir, "list_things.json"), []byte(`[1, 2, 3]`), 0o644); err != nil {
		t.Fatalf("write example: %v", err)
	}

	var code int
	_, stderr := captureOutput(t, func() {
		code = apisCmd([]string{"validate", packPath})
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
	if !strings.Contains(stderr, "list_things") {
		t.Fatalf("stderr does not name the failing op: %q", stderr)
	}
}

func TestApisValidateEnvelopeErrorWhen(t *testing.T) {
	dir := t.TempDir()
	pack := `pack: demo
version: 1
envelope:
  error_when: '.failed'
  error_message: '.msg'
ops:
  get_thing:
    get: /things/{id}
    params:
      id: { pattern: '^\d+$' }
`
	packPath := filepath.Join(dir, "demo.yaml")
	if err := os.WriteFile(packPath, []byte(pack), 0o644); err != nil {
		t.Fatalf("write pack: %v", err)
	}
	examplesDir := filepath.Join(dir, "examples")
	if err := os.MkdirAll(examplesDir, 0o755); err != nil {
		t.Fatalf("mkdir examples: %v", err)
	}
	if err := os.WriteFile(filepath.Join(examplesDir, "get_thing.json"), []byte(`{"failed": true, "msg": "boom"}`), 0o644); err != nil {
		t.Fatalf("write example: %v", err)
	}

	var code int
	_, stderr := captureOutput(t, func() {
		code = apisCmd([]string{"validate", packPath})
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
	if !strings.Contains(stderr, "get_thing") || !strings.Contains(stderr, "boom") {
		t.Fatalf("stderr does not report the envelope error: %q", stderr)
	}
}

func TestApisValidateMissingPath(t *testing.T) {
	path := filepath.Join(t.TempDir(), "does-not-exist.yaml")

	var code int
	captureOutput(t, func() {
		code = apisCmd([]string{"validate", path})
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
}

func TestApisValidateNoExamplesDir(t *testing.T) {
	dir := t.TempDir()
	packPath := filepath.Join(dir, "demo.yaml")
	if err := os.WriteFile(packPath, []byte(demoPackYAML), 0o644); err != nil {
		t.Fatalf("write pack: %v", err)
	}

	var code int
	stdout, _ := captureOutput(t, func() {
		code = apisCmd([]string{"validate", packPath})
	})
	if code != exitcode.OK {
		t.Fatalf("exit code = %d, want %d", code, exitcode.OK)
	}
	if !strings.Contains(stdout, "without examples") {
		t.Fatalf("stdout does not report a missing example: %q", stdout)
	}
}

// --- argsFlag ---

func TestArgsFlagStringValue(t *testing.T) {
	var a argsFlag
	if err := a.Set("name=demo"); err != nil {
		t.Fatalf("Set: %v", err)
	}
	if a["name"] != "demo" {
		t.Errorf("a[name] = %#v, want the string %q", a["name"], "demo")
	}
}

func TestArgsFlagJSONNumber(t *testing.T) {
	var a argsFlag
	if err := a.Set("id:=123"); err != nil {
		t.Fatalf("Set: %v", err)
	}
	if a["id"] != float64(123) {
		t.Errorf("a[id] = %#v, want float64(123)", a["id"])
	}
}

func TestArgsFlagJSONBool(t *testing.T) {
	var a argsFlag
	if err := a.Set("active:=true"); err != nil {
		t.Fatalf("Set: %v", err)
	}
	if a["active"] != true {
		t.Errorf("a[active] = %#v, want true", a["active"])
	}
}

func TestArgsFlagJSONArray(t *testing.T) {
	var a argsFlag
	if err := a.Set("ids:=[1,2]"); err != nil {
		t.Fatalf("Set: %v", err)
	}
	list, ok := a["ids"].([]any)
	if !ok || len(list) != 2 {
		t.Fatalf("a[ids] = %#v, want a two-element list", a["ids"])
	}
}

func TestArgsFlagBadJSON(t *testing.T) {
	var a argsFlag
	err := a.Set("id:={not json}")
	if err == nil {
		t.Fatalf("Set succeeded, want an error for invalid JSON")
	}
	if !strings.Contains(err.Error(), "invalid JSON value") {
		t.Errorf("error = %v, want it to say invalid JSON value", err)
	}
}

func TestArgsFlagMissingEquals(t *testing.T) {
	var a argsFlag
	err := a.Set("no-equals-here")
	if err == nil {
		t.Fatalf("Set succeeded, want an error for a missing =")
	}
	if !strings.Contains(err.Error(), "expected k=v or k:=<json>") {
		t.Errorf("error = %v, want it to say the expected form", err)
	}
}

func TestArgsFlagRepeatedKeyOverwrites(t *testing.T) {
	var a argsFlag
	if err := a.Set("name=first"); err != nil {
		t.Fatalf("Set: %v", err)
	}
	if err := a.Set("name=second"); err != nil {
		t.Fatalf("Set: %v", err)
	}
	if a["name"] != "second" {
		t.Errorf("a[name] = %#v, want %q", a["name"], "second")
	}
}

// --- apis call ---

// callPackYAML is a minimal pack with one readonly GET op whose transform
// picks a field out of the response, and whose base_url is left to the
// scenario's apis entry.
const callPackYAML = `pack: demo
version: 1
config:
  base_url: {}
ops:
  get_thing:
    get: /things/{id}
    readonly: true
    params:
      id: { pattern: '^\d+$' }
    transform: '{ id: .id, name: .name }'
`

// writeCallScenario writes a scenario whose single apis entry points at a
// pack directory laid out as demo/demo.yaml, with base_url set to the test
// server, plus one no-op step: a scenario without any step fails validation.
func writeCallScenario(t *testing.T, dir, baseURL string) string {
	t.Helper()
	apisDir := filepath.Join(dir, "apis")
	if err := os.MkdirAll(apisDir, 0o755); err != nil {
		t.Fatalf("mkdir apis: %v", err)
	}
	if err := os.WriteFile(filepath.Join(apisDir, "demo.yaml"), []byte(callPackYAML), 0o644); err != nil {
		t.Fatalf("write pack: %v", err)
	}
	scenarioYAML := `
version: 1
name: apis-call
apis:
  demo:
    pack: demo
    from: ./apis/
    config:
      base_url: "` + baseURL + `"
steps:
  - id: noop
    run: "echo hi"
`
	path := filepath.Join(dir, "s.yaml")
	if err := os.WriteFile(path, []byte(scenarioYAML), 0o644); err != nil {
		t.Fatalf("write scenario: %v", err)
	}
	return path
}

// 1. The happy path: the call goes through the scenario's apis entry, the
// response comes back transformed, and stdout is the transformed JSON.
func TestApisCallHappyPath(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/things/7" {
			t.Errorf("server saw path %q, want /things/7", r.URL.Path)
		}
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(`{"id":7,"name":"demo"}`))
	}))
	defer server.Close()

	dir := t.TempDir()
	scenarioPath := writeCallScenario(t, dir, server.URL)

	var code int
	stdout, stderr := captureOutput(t, func() {
		code = apisCmd([]string{"call", scenarioPath, "demo.get_thing", "-a", "id:=7"})
	})
	if code != exitcode.OK {
		t.Fatalf("exit code = %d, want %d (stderr: %s)", code, exitcode.OK, stderr)
	}
	var got map[string]any
	if err := json.Unmarshal([]byte(stdout), &got); err != nil {
		t.Fatalf("stdout does not parse as JSON: %v\n%s", err, stdout)
	}
	if got["name"] != "demo" {
		t.Errorf("result[name] = %#v, want demo", got["name"])
	}
	if got["id"] != float64(7) {
		t.Errorf("result[id] = %#v, want 7", got["id"])
	}
}

// 2. Wrong positional count is a configuration error, before anything loads.
func TestApisCallWrongPositionalCount(t *testing.T) {
	dir := t.TempDir()
	scenarioPath := writeCallScenario(t, dir, "http://example.invalid")

	var code int
	_, stderr := captureOutput(t, func() {
		code = apisCmd([]string{"call", scenarioPath})
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
	if !strings.Contains(stderr, "Usage:") {
		t.Errorf("stderr = %q, want the usage", stderr)
	}
}

// 3. A malformed -a argument is a configuration error.
func TestApisCallBadArgSpec(t *testing.T) {
	dir := t.TempDir()
	scenarioPath := writeCallScenario(t, dir, "http://example.invalid")

	var code int
	captureOutput(t, func() {
		code = apisCmd([]string{"call", scenarioPath, "demo.get_thing", "-a", "no-equals-here"})
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
}

// 4. An api name the scenario does not declare is a configuration error.
func TestApisCallUnknownAPI(t *testing.T) {
	dir := t.TempDir()
	scenarioPath := writeCallScenario(t, dir, "http://example.invalid")

	var code int
	_, stderr := captureOutput(t, func() {
		code = apisCmd([]string{"call", scenarioPath, "nope.get_thing", "-a", "id:=7"})
	})
	if code != exitcode.Config {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Config)
	}
	if !strings.Contains(stderr, "nope") {
		t.Errorf("stderr = %q, want the unknown api named", stderr)
	}
}

// 5. A server error surfaces as a plain failure, not a configuration error:
// the scenario and the call were both fine, the service just failed.
func TestApisCallServerError(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
	}))
	defer server.Close()

	dir := t.TempDir()
	scenarioPath := writeCallScenario(t, dir, server.URL)

	var code int
	captureOutput(t, func() {
		code = apisCmd([]string{"call", scenarioPath, "demo.get_thing", "-a", "id:=7"})
	})
	if code != exitcode.Failure {
		t.Fatalf("exit code = %d, want %d", code, exitcode.Failure)
	}
}

// TestApisValidateShippedPacks runs `apis validate` over every pack this
// repository ships, so that a pack breaks in the test suite rather than in a
// scenario: the recorded examples are the only check a pack gets without a
// live API to call.
func TestApisValidateShippedPacks(t *testing.T) {
	entries, err := os.ReadDir("../../apis")
	if err != nil {
		t.Fatalf("read apis/: %v", err)
	}
	var paths []string
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() {
			if name == "examples" {
				continue // the examples of the single-file packs beside it
			}
			paths = append(paths, filepath.Join("../../apis", name))
			continue
		}
		if strings.HasSuffix(name, ".yaml") {
			paths = append(paths, filepath.Join("../../apis", name))
		}
	}
	if len(paths) == 0 {
		t.Fatal("no packs found under apis/")
	}

	var code int
	_, stderr := captureOutput(t, func() {
		code = apisCmd(append([]string{"validate"}, paths...))
	})
	if code != exitcode.OK {
		t.Fatalf("apis validate %v = %d, want %d: %s", paths, code, exitcode.OK, stderr)
	}
}
