package schemadoc

import (
	_ "embed"
	"encoding/json"
)

// labels are the words the generator itself contributes to the document. The
// prose of the fields comes from the schema and is translated separately.
type labels struct {
	title         string
	intro         string
	generated     string
	definitions   string
	field         string
	typeLabel     string
	required      string
	description   string
	yes           string
	no            string
	closed        string
	or            string
	arrayOf       string
	mapOf         string
	defaultLabel  string
	pattern       string
	format        string
	minimum       string
	maximum       string
	minItems      string
	minProperties string
	objectForm    string
}

var labelSets = map[string]labels{
	"en": {
		title:         "Scenario schema reference",
		intro:         "Generated from the JSON Schema that `baton schema` prints, so it always describes the format this build accepts.",
		generated:     "Generated by `make docs` from internal/scenario/scenario.schema.json. Do not edit by hand.",
		definitions:   "Definitions",
		field:         "Field",
		typeLabel:     "Type",
		required:      "Required",
		description:   "Description",
		yes:           "yes",
		no:            "no",
		closed:        "No other fields are allowed.",
		or:            " or ",
		arrayOf:       "array of %s",
		mapOf:         "map of name to %s",
		defaultLabel:  "Default",
		pattern:       "Pattern",
		format:        "Format",
		minimum:       "Minimum",
		maximum:       "Maximum",
		minItems:      "At least items:",
		minProperties: "At least fields:",
		objectForm:    "object form",
	},
	"ru": {
		title:         "Справочник схемы сценария",
		intro:         "Сгенерирован из JSON Schema, которую печатает `baton schema`, поэтому всегда описывает формат, принимаемый этой сборкой.",
		generated:     "Сгенерировано `make docs` из internal/scenario/scenario.schema.json. Не редактировать вручную.",
		definitions:   "Определения",
		field:         "Поле",
		typeLabel:     "Тип",
		required:      "Обязательное",
		description:   "Описание",
		yes:           "да",
		no:            "нет",
		closed:        "Другие поля не допускаются.",
		or:            " или ",
		arrayOf:       "массив из %s",
		mapOf:         "отображение имени в %s",
		defaultLabel:  "По умолчанию",
		pattern:       "Шаблон",
		format:        "Формат",
		minimum:       "Минимум",
		maximum:       "Максимум",
		minItems:      "Элементов не менее:",
		minProperties: "Полей не менее:",
		objectForm:    "объектная форма",
	},
}

// russian maps the English prose of the schema to its Russian translation. A
// description without an entry falls back to the English text, so a new line
// in the schema shows up untranslated instead of disappearing.
//
//go:embed ru.json
var russianJSON []byte

// translator returns the function that localises a description of the schema.
func translator(lang string) func(string) string {
	if lang != "ru" {
		return func(text string) string { return text }
	}
	translations := map[string]string{}
	if err := json.Unmarshal(russianJSON, &translations); err != nil {
		return func(text string) string { return text }
	}
	return func(text string) string {
		if translated, ok := translations[text]; ok {
			return translated
		}
		return text
	}
}
