// Package openapi turns an OpenAPI 3 document into the skeleton of a baton
// API pack (spec section 7.4.7). It backs the `baton apis import` command.
//
// libopenapi is a build-time dependency only: the generated pack never
// references it, and neither does any other runtime package. The generator
// derives what the document can honestly tell it (paths, methods, argument
// types, authorisation schemes) and leaves the judgement calls -- transforms,
// descriptions, readonly, pagination -- to the pack author as TODO markers.
package openapi

import (
	"errors"
	"fmt"
	"net/url"
	"regexp"
	"slices"
	"strings"

	"github.com/pb33f/libopenapi"
	"github.com/pb33f/libopenapi/datamodel"
	"github.com/pb33f/libopenapi/datamodel/high/base"
	v3 "github.com/pb33f/libopenapi/datamodel/high/v3"
	yamlv4 "go.yaml.in/yaml/v4"
	"gopkg.in/yaml.v3"
)

// Options tunes what Import writes into the skeleton.
type Options struct {
	// Name is the pack name; empty falls back to a slug of the document title.
	Name string
	// Ops names the operationIds to import; it must not be empty.
	Ops []string
	// Interface names the pack interface the author intends to implement, and
	// only adds a commented placeholder: the generator cannot guess which
	// interface operation an operationId stands for.
	Interface string
}

// Import turns the chosen operations of an OpenAPI document into the
// skeleton of an API pack (spec section 7.4.7). The document is not used at
// run time, so the skeleton carries every field the runner needs and leaves
// the judgement calls -- transforms, descriptions, readonly, pagination --
// to the author.
func Import(spec []byte, opts Options) ([]byte, error) {
	if len(opts.Ops) == 0 {
		return nil, errors.New("ops: required, name the operationIds to import")
	}
	if dup := firstDuplicate(opts.Ops); dup != "" {
		return nil, fmt.Errorf("ops: %q is requested twice", dup)
	}

	doc, err := libopenapi.NewDocument(spec)
	if err != nil {
		return nil, fmt.Errorf("openapi: %w", err)
	}
	// BuildV3Model happily tries to coerce a Swagger 2.0 document and fails
	// with a confusing error, so the version is checked up front.
	if info := doc.GetSpecInfo(); info != nil && info.SpecFormat == datamodel.OAS2 {
		return nil, errors.New("openapi: swagger 2.0 is not supported, convert the document to openapi 3 first")
	}
	built, errs := doc.BuildV3Model()
	if errs != nil {
		return nil, fmt.Errorf("openapi: %w", errs)
	}
	if built == nil {
		return nil, errors.New("openapi: document produced no model")
	}
	model := &built.Model

	entries, err := selectOps(model, opts.Ops)
	if err != nil {
		return nil, err
	}
	auth := resolveAuth(model)

	var b strings.Builder
	b.WriteString("# generated by baton apis import, fill in the transforms and descriptions\n")

	packName := opts.Name
	if packName == "" {
		packName = slugify(documentTitle(model))
	}
	fmt.Fprintf(&b, "pack: %s\n", packName)
	b.WriteString("version: 1\n")
	fmt.Fprintf(&b, "description: %s\n", quote(documentDescription(model)))
	b.WriteString("\n")

	b.WriteString("config:\n")
	if base, ok := absoluteServerURL(model); ok {
		fmt.Fprintf(&b, "  base_url: { default: %s }\n", quote(base))
	} else {
		b.WriteString("  base_url: { required: true }\n")
	}
	if auth.needsUser {
		// the basic scheme reads the username from config.user; the pack
		// validator rejects a basic scheme whose config field is missing.
		b.WriteString("  user: { required: true }\n")
	}
	b.WriteString("\n")

	writeAuth(&b, auth)
	b.WriteString("\n")

	b.WriteString("ops:\n")
	used := map[string]bool{}
	for _, e := range entries {
		key := uniqueKey(toIdent(e.id), used)
		if err := writeOp(&b, key, e, opts.Interface); err != nil {
			return nil, err
		}
	}

	return []byte(b.String()), nil
}

// firstDuplicate returns the first name that appears twice in ids, or "".
func firstDuplicate(ids []string) string {
	seen := map[string]bool{}
	for _, id := range ids {
		if seen[id] {
			return id
		}
		seen[id] = true
	}
	return ""
}

// opEntry is one operation the caller asked to import, resolved against the
// document.
type opEntry struct {
	id     string
	method string
	path   string
	op     *v3.Operation
}

// restMethods are the methods the pack format can express as an operation.
var restMethods = map[string]bool{"get": true, "post": true, "put": true, "patch": true, "delete": true}

// selectOps resolves every requested operationId against the document's
// paths, in the order the caller asked for.
func selectOps(model *v3.Document, ids []string) ([]opEntry, error) {
	byID := map[string]opEntry{}
	var known []string
	if model.Paths != nil && model.Paths.PathItems != nil {
		for pathPair := model.Paths.PathItems.Oldest(); pathPair != nil; pathPair = pathPair.Next() {
			path := pathPair.Key
			for opPair := pathPair.Value.GetOperations().Oldest(); opPair != nil; opPair = opPair.Next() {
				operation := opPair.Value
				if operation.OperationId == "" {
					continue
				}
				byID[operation.OperationId] = opEntry{
					id:     operation.OperationId,
					method: opPair.Key,
					path:   path,
					op:     operation,
				}
				known = append(known, operation.OperationId)
			}
		}
	}

	entries := make([]opEntry, 0, len(ids))
	for _, id := range ids {
		e, ok := byID[id]
		if !ok {
			return nil, unknownOpError(id, known)
		}
		if !restMethods[e.method] {
			return nil, fmt.Errorf("ops.%s: method %s is not one of get, post, put, patch, delete", id, e.method)
		}
		entries = append(entries, e)
	}
	return entries, nil
}

// unknownOpError reports an operationId the document does not have, listing
// up to ten operationIds it does have, sorted, so the caller can pick one.
func unknownOpError(id string, known []string) error {
	sorted := slices.Clone(known)
	slices.Sort(sorted)
	sorted = slices.Compact(sorted)
	if len(sorted) > 10 {
		sorted = sorted[:10]
	}
	if len(sorted) == 0 {
		return fmt.Errorf("ops: %q is not an operationId of the document, which declares none", id)
	}
	return fmt.Errorf("ops: %q is not an operationId of the document, it has: %s", id, strings.Join(sorted, ", "))
}

// documentTitle and documentDescription read the two info fields the
// skeleton can honestly derive a name and a description from.
func documentTitle(model *v3.Document) string {
	if model.Info == nil {
		return ""
	}
	return model.Info.Title
}

func documentDescription(model *v3.Document) string {
	if model.Info == nil {
		return ""
	}
	if model.Info.Title != "" {
		return model.Info.Title
	}
	return model.Info.Summary
}

// absoluteServerURL returns the first server URL of the document that is
// usable as a default base_url, i.e. an absolute URL rather than a bare path.
func absoluteServerURL(model *v3.Document) (string, bool) {
	for _, srv := range model.Servers {
		if srv == nil || srv.URL == "" {
			continue
		}
		u, err := url.Parse(srv.URL)
		if err != nil || !u.IsAbs() {
			continue
		}
		return srv.URL, true
	}
	return "", false
}

// slugify turns a document title into a pack name matching the pack format's
// naming rule (lowercase, starts with a letter, - and _ allowed).
func slugify(s string) string {
	lower := strings.ToLower(s)
	slug := slugInvalidRe.ReplaceAllString(lower, "-")
	slug = strings.Trim(slug, "-")
	if slug == "" {
		return "pack"
	}
	if slug[0] < 'a' || slug[0] > 'z' {
		slug = "pack-" + slug
	}
	return slug
}

var slugInvalidRe = regexp.MustCompile(`[^a-z0-9]+`)

// toIdent turns an arbitrary OpenAPI name (an operationId or a parameter
// name) into an identifier the pack format accepts: lowercase, starting with
// a letter, only letters, digits and underscores. camelCase and kebab-case
// names both turn into snake_case.
func toIdent(s string) string {
	withBoundaries := identCamelRe.ReplaceAllString(s, "${1}_$2")
	lower := strings.ToLower(withBoundaries)
	ident := identInvalidRe.ReplaceAllString(lower, "_")
	for strings.Contains(ident, "__") {
		ident = strings.ReplaceAll(ident, "__", "_")
	}
	ident = strings.Trim(ident, "_")
	if ident == "" {
		return "x"
	}
	if ident[0] < 'a' || ident[0] > 'z' {
		ident = "x_" + ident
	}
	return ident
}

var (
	identCamelRe   = regexp.MustCompile(`([a-z0-9])([A-Z])`)
	identInvalidRe = regexp.MustCompile(`[^a-z0-9_]+`)
)

// uniqueKey appends a numeric suffix when base was already used, so two
// operations that turn into the same identifier do not collide in the ops
// map.
func uniqueKey(base string, used map[string]bool) string {
	key := base
	for i := 2; used[key]; i++ {
		key = fmt.Sprintf("%s_%d", base, i)
	}
	used[key] = true
	return key
}

// quote renders s as a YAML scalar, quoting it only when a plain scalar
// would not read back as a string (e.g. "true" or "1.5") or would not be
// plain at all inside a flow mapping: params are rendered as "{ a: b }", and
// a flow indicator such as the "[" of a pattern would start a nested
// collection there. This is the only string quoting the generator does;
// hand-editing the rest is expected.
func quote(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	node := yaml.Node{}
	node.SetString(s)
	if strings.ContainsAny(s, ",[]{}") {
		node.Style = yaml.SingleQuotedStyle
	}
	var out strings.Builder
	enc := yaml.NewEncoder(&out)
	if err := enc.Encode(&node); err != nil {
		// SetString never produces a node yaml.v3 cannot encode; this is
		// unreachable in practice, but a raw fallback keeps Import total.
		return s
	}
	_ = enc.Close()
	return strings.TrimRight(out.String(), "\n")
}

// schemaOf returns the schema behind a proxy, or nil when there is none.
func schemaOf(sp *base.SchemaProxy) *base.Schema {
	if sp == nil {
		return nil
	}
	return sp.Schema()
}

// primaryType picks the one JSON Schema type that matters for a parameter,
// ignoring the "null" a 3.1 schema adds for nullable fields. It returns ""
// when the type is missing or genuinely ambiguous, which the caller treats
// as "the generator does not know this type".
func primaryType(types []string) string {
	found := ""
	for _, t := range types {
		if t == "null" {
			continue
		}
		if found != "" && found != t {
			return ""
		}
		found = t
	}
	return found
}

// paramPattern derives the pattern a path or query parameter needs to pass
// pack validation, from its JSON Schema type. todo is a trailing comment for
// patterns that are deliberately loose.
func paramPattern(t string) (pattern, todo string, err error) {
	switch t {
	case "integer":
		return `^\d+$`, "", nil
	case "number":
		return `^-?\d+(\.\d+)?$`, "", nil
	case "boolean":
		return `^(true|false)$`, "", nil
	case "string":
		return `^[\w./-]+$`, "TODO: narrow the pattern", nil
	default:
		return "", "", errors.New("has no type the generator can turn into a pattern, add params by hand")
	}
}

// enumPattern builds a pattern that admits exactly the values of a string
// enum. It returns "" when a value is not a plain scalar, leaving the
// type-derived pattern in place.
func enumPattern(nodes []*yamlv4.Node) string {
	alts := make([]string, 0, len(nodes))
	for _, n := range nodes {
		if n == nil || n.Kind != yamlv4.ScalarNode || n.Value == "" {
			return ""
		}
		alts = append(alts, regexp.QuoteMeta(n.Value))
	}
	if len(alts) == 0 {
		return ""
	}
	return "^(" + strings.Join(alts, "|") + ")$"
}

// renderDefault renders the default value of a schema as a YAML scalar,
// preserving whatever type the document declared it with: an unquoted
// !!bool/!!int/!!float value renders as-is, anything else (usually !!str)
// goes through quote.
func renderDefault(n *yamlv4.Node) string {
	if n == nil || n.Kind != yamlv4.ScalarNode {
		return ""
	}
	switch n.Tag {
	case "!!bool", "!!int", "!!float", "!!null":
		return n.Value
	default:
		return quote(n.Value)
	}
}

// enumValues renders a string enum as the elements of a YAML flow sequence.
func enumValues(nodes []*yamlv4.Node) []string {
	values := make([]string, 0, len(nodes))
	for _, n := range nodes {
		if n == nil {
			continue
		}
		values = append(values, quote(n.Value))
	}
	return values
}
